url: http://bingnaive.github.io
author: 张冰冰
title: 个人技术博客
description: Gray - Single column blog and portfolio Jekyll theme
github_username: bingNaive
logo: 
image: 
social:
  name: 天真
  links:
    - https://github.com/bingNaive

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate  #分页
  - jekyll-gist    #可以插入git代码块
  # - jekyll-seo-tag  #更好的被搜索引擎抓取
  - jekyll-sitemap   #站点地图
  # - disqus-for-jekyll   #评论插件

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  art:
    output: true
    permalink: /art/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
